# This one will be applied by wego (for now kubectl apply)
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-config
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: godays-demo
  url: https://github.com/cdavisafc/podinfo-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: goat-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./.wego/targets/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-config
  validation: client
